version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db_trokka
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_trokka
      MYSQL_USER: api_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"